version: '3.4'

services:
  fc.abreubarber.db:
    container_name: abreubarberdb
    hostname:  abreubarberdb
    image: mysql
    ports:
     - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: '@BREU123'
  